[project]
name = "first-repo"
version = "0.1.0"
description = "Just practice..."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = ["pre-commit"]

[dependency-groups]
dev = ["pre-commit"]
